name: Test Pull Request

on:
  pull_request:
    branches:
      - main
  
  # run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set GOOGLE_APPLICATION_CREDENTIALS (Secure Approach)
        uses: google-github-actions/auth@v2  # Assuming you have this action installed
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Build with Gradle
        run: ./gradlew build
        env:
          SPRING_PROFILES_ACTIVE: postgres-cloud
          SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
          DATABASE_URL: ${{ secrets.TESTING_DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.TESTING_DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.TESTING_DATABASE_PASSWORD }}

      - name: Test with Gradle
        run: ./gradlew test
